[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
panic = "abort"

[dependencies]
itertools = "0.10.5"
ndarray = "0.15.6"
nom = "7.1.1"
num = "0.4.0"
once_cell = "1.16.0"
regex = "1.7.0"
intervallum = "1.4.0"
gcollections = "1.5.0"
